### ISSUE TITLE
TypeError: dropzone__WEBPACK_IMPORTED_MODULE_1__ is not a constructor

### ISSUE THREAD

**Issue by Cristhianzl** [zefoy/ngx-dropzone-wrapper#151]
Hello,

All the dropzones that I'm using in my project stoped working from nothing.
I tried to go to in the past few weeks commits and check if was something new in the project, but seems like Angular just dont reconize the component.

Does anyone knows how to fix it?

Thanks a lot!

![dropzone](https://user-images.githubusercontent.com/72977554/109031225-48ea6600-76a3-11eb-96a4-535be4fe3276.PNG)

**Comment by Cristhianzl** [comment]
SOLVED:

It was just uninstall the 2 packages:

npm uninstall ngx-dropzone-wrapper
npm uninstall dropzone

and them install again the packages in the newest version:

npm i dropzone
npm i ngx-dropzone-wrapper

**Comment by Nascooo** [comment]
@Cristhianzl  
I have the similar Issue but it didn't Work
Could you Mention which version of DropZone & DropZone-Wrapper you are using : 
i'm using  `"dropzone": "5.7.6"` &  `"ngx-dropzone-wrapper": "^6.2.0"`

**Comment by Cristhianzl** [comment]
> @Cristhianzl
> I have the similar Issue but it didn't Work
> Could you Mention which version of DropZone & DropZone-Wrapper you are using :
> i'm using `"dropzone": "5.7.6"` & `"ngx-dropzone-wrapper": "^6.2.0"`

Hello Nasco,

Im using these 2 versions:
"dropzone": "^5.7.6"
"ngx-dropzone-wrapper": "^10.0.1"

Maybe if you update your dropzone-wrapper as I did, works!

**Comment by gowthamandev** [comment]
Hi,
I too facing the same issue, it is working when updating the "ngx-dropzone-wrapper" version "^8.0.0" to "^10.0.0", but I need a permanent solution because I am using this in an Enterprise application, it should not happen again right? is there any other way to solve this issue permanently, why this was happen? @sconix pls help me

**Comment by sconix** [comment]
Thats what the package lock files are for, making certain that certain versions are installed. At least can not see any other reason than your installed package versions changing.

**Comment by sobelfall** [comment]
I use angular 13 and version 11.0.0 but reproduce this issue

**Comment by sobelfall** [comment]
fixed here https://github.com/Liquid-JS/nxt-dropzone-wrapper

**Comment by adamhathcock** [comment]
verison 11.0.0 has this issue for me.

Downgrading to 10.0.1 or using the other package above works for me

**Comment by lazaro3487** [comment]
I have the same problem with version 7, 8 and 11. Only version 10 works for me.

Angular version 7.2.16

**Comment by wratho** [comment]
Still seeing this issue with Angular 14 with version 11

**Comment by smandal92** [comment]
Error getting in console: ---
DropzoneComponent.html:1 ERROR TypeError: Dropzone is not a constructor
at dropzone.directive.js:58:1
at webpackJsonp.../../../../zone.js/dist/zone.js.ZoneDelegate.invoke (zone.js:388:1)
at webpackJsonp.../../../../zone.js/dist/zone.js.Zone.run (zone.js:138:1)
at webpackJsonp.../../../core/esm5/core.js.NgZone.runOutsideAngular (core.js:4708:48)
at webpackJsonp.../../../../ngx-dropzone-wrapper/dist/lib/dropzone.directive.js.DropzoneDirective.ngOnInit (dropzone.directive.js:57:1)
at checkAndUpdateDirectiveInline (core.js:12411:1)
at checkAndUpdateNodeInline (core.js:13935:1)
at checkAndUpdateNode (core.js:13878:1)
at debugCheckAndUpdateNode (core.js:14771:50)
at debugCheckDirectivesFn (core.js:14712:1)

Added in .ts file in angular project:
import { DropzoneModule, DROPZONE_CONFIG, DropzoneConfigInterface, DropzoneComponent } from 'ngx-dropzone-wrapper';

Angular version: "@angular/core": "^5.2.4",

Can you give any idea how to fix this issue.
Thankyou in advance

**Comment by wratho** [comment]
this issue appears to still exist in the version 12? This seems like a pretty bad issue... and updates on an actual resolution?

**Comment by queejie** [comment]
Seeing this for the first time, with an upgrade to Angular 14.2.5.  Is there a known workaround.  Thank you.

**Comment by queejie** [comment]
> SOLVED:
> 
> It was just uninstall the 2 packages:
> 
> npm uninstall ngx-dropzone-wrapper npm uninstall dropzone
> 
> and them install again the packages in the newest version:
> 
> npm i dropzone npm i ngx-dropzone-wrapper

This did not work.

**Comment by queejie** [comment]
> fixed here https://github.com/Liquid-JS/nxt-dropzone-wrapper
This does indeed fix it, but it looks like they're getting out of sync.  Would it be possible to incorporate this back into the main library?  Thanks very much for this wrapper.

**Comment by dqjauthentrics** [comment]
@lazaro3487 It's been awhile, and I don't remember what has happened in the interim, but I am using ngx-dropzone-wrapper 13.0.0 with Angular 15 and it was working with Angular 14 as well.
